# https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html-single/installing_an_on-premise_cluster_with_the_agent-based_installer/index#agent-host-roles_preparing-to-install-with-agent-based-installer
apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: zrphd
rendezvousIP: 192.168.28.21 # read about rendezvousIP & DHCP
hosts:
- hostname: master-1
  role: master
  rootDeviceHints:
    deviceName: "/dev/sda"
  interfaces:
  - name: ens192
    macAddress: 00:50:56:00:00:01
  networkConfig:
    interfaces:
    - name: ens192
      type: ethernet
      state: up
      mac-address: 00:50:56:00:00:01
      ipv4:
        enabled: true
        address:
        - ip: 192.168.28.21
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 192.168.28.11
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.28.1
        next-hop-interface: ens192
        table-id: 254
- hostname: master-2
  role: master
  rootDeviceHints:
    deviceName: "/dev/sda"
  interfaces:
  - name: ens192
    macAddress: 00:50:56:00:00:02
  networkConfig:
    interfaces:
    - name: ens192
      type: ethernet
      state: up
      mac-address: 00:50:56:00:00:02
      ipv4:
        enabled: true
        address:
        - ip: 192.168.28.22
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 192.168.28.11
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.28.1
        next-hop-interface: ens192
        table-id: 254
- hostname: master-3
  role: master
  rootDeviceHints:
    deviceName: "/dev/sda"
  interfaces:
  - name: ens192
    macAddress: 00:50:56:00:00:03
  networkConfig:
    interfaces:
    - name: ens192
      type: ethernet
      state: up
      mac-address: 00:50:56:00:00:03
      ipv4:
        enabled: true
        address:
        - ip: 192.168.28.23
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 192.168.28.11
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.28.1
        next-hop-interface: ens192
        table-id: 254
- hostname: worker-1
  role: worker
  interfaces:
  - name: ens192
    macAddress: 00:50:56:00:00:04
  networkConfig:
    interfaces:
    - name: ens192
      type: ethernet
      state: up
      mac-address: 00:50:56:00:00:04
      ipv4:
        enabled: true
        address:
        - ip: 192.168.28.31
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 192.168.28.11
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.28.1
        next-hop-interface: ens192
        table-id: 254
- hostname: worker-2
  role: worker
  interfaces:
  - name: ens192
    macAddress: 00:50:56:00:00:05
  networkConfig:
    interfaces:
    - name: ens192
      type: ethernet
      state: up
      mac-address: 00:50:56:00:00:05
      ipv4:
        enabled: true
        address:
        - ip: 192.168.28.32
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 192.168.28.11
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.28.1
        next-hop-interface: ens192
        table-id: 254
- hostname: worker-3
  role: worker
  interfaces:
  - name: ens192
    macAddress: 00:50:56:00:00:06
  networkConfig:
    interfaces:
    - name: ens192
      type: ethernet
      state: up
      mac-address: 00:50:56:00:00:06
      ipv4:
        enabled: true
        address:
        - ip: 192.168.28.33
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 192.168.28.11
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.28.1
        next-hop-interface: ens192
        table-id: 254
